### ISSUE TITLE
Problème dans la création de base de données MyWebIntelligence 

### ISSUE THREAD

**Issue by Arnaudprod26** [MyWebIntelligence/MyWebIntelligencePython#27]
Bonjour, 
Je rencontre un soucis concernant l'installation de MywebIntelligence. 
Toute les étapes de l'installation fonctionne parfaitement, mais en arrivant à la phase de création de la base de données, avec la commande : `# python mywi.py db setup`, Je me retrouves avec les messages d'erreur suivant : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mywi.py", line 11, in <module>
    main()
  File "/app/mywi.py", line 7, in main
    cli.command_input()
  File "/app/mwi/cli.py", line 81, in command_input
    dispatch(args)
  File "/app/mwi/cli.py", line 116, in dispatch
    return call(controller.get(args.verb), args)
  File "/app/mwi/cli.py", line 128, in call
    return func(args)
  File "/app/mwi/controller.py", line 31, in setup
    model.DB.drop_tables(tables)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3373, in drop_tables
    model.drop_table(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6767, in drop_table
    cls._schema.drop_all(safe, drop_sequences, **options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5871, in drop_all
    self.drop_table(safe, **options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5744, in drop_table
    self.database.execute(self._drop_table(safe=safe, **options))
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3190, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3174, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
```
Je ne sais pas comment résoudre ce problème. 

Merci par avance pour votre aide et bonne journée !

**Comment by neoxium** [comment]
Bonjour @Arnaudprod26 je pense que le setup de la DB cherche à supprimer les tables d'une DB qui n'existe pas encore. Le temps de résoudre ce bug, je vous suggère de créer vous-même la DB

**Comment by neoxium** [comment]
Bonjour @Arnaudprod26 je pense que le setup tente de supprimer des tables de la DB qui n'existent pas encore. Comme le bug ne sera pas corrigé dans l'immédiat, le solution serait de créer la DB au préalable. Pour vous faciliter la tâche vous trouverez le fichier DB vide à placer dans votre répertoire data et relancer le `db setup`.

[mwi.zip](https://github.com/user-attachments/files/17648008/mwi.zip)

**Comment by Arnaudprod26** [comment]
Merci beaucoup @neoxium pour cette réponse ! 
Cependant même en prenant votre fichier, et en le mettant dans mon dossier data, la commande `db setup` me donne la même erreur. 
Mais je peux attendre sans problème le correctif de ce bug, je souhaitais simplement tester MyWebIntelligence pour voir ces possibilités dans le cadre de mon travail de thèse. 

Merci encore pour cette réponse.

**Comment by neoxium** [comment]
Bonjour @Arnaudprod26 j'ai pu reproduire l'environnement et lancer le setup sans erreur. Il est en réalité probable que le chemin vers votre dossier `data` configuré dans votre fichier `settings.py` ne soit pas valide, assurez-vous que le chemin est correct.

Si vous avez créé votre projet dans un environnement virtuel Python, sous Windows, avec des slash (et non des antislash) :

`data_location = 'C:/Path/To/data'`

Sinon sous Docker, avec le dossier `data` local monté à la racine :

`data_location = '/data'`

**Comment by Arnaudprod26** [comment]
Bonjour @neoxium, 

Effectivement, le souci venait de là, j'ai enfin pu créer la base de données !  
Merci beaucoup pour votre aide !
